### ISSUE TITLE
refactor :tar task

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand-packaging#114]
With OSC/ondemand#1466 it's clear RHEL and debian have different expectations around the source tar.

This ticket is to refactor the `rake package:tar` task such that it will work for both distros. I'm going to throw package versioning in here too, there's a few ways to set and determine the version.  And debian doesn't work well with `v` prefixed versions. So the 2 issues are certainly related because the tar file has the version in it in both distros.

**Comment by treydock** [comment]
Closing via #161
