### ISSUE TITLE
build out of source tree

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand-packaging#115]
One item that might be handled with this or warrant a new issue, is builds with containers should NOT build from within the source tree. Instead a tar.gz and other sources files should be copied to some location like /tmp/work or something (can be mounted to host) and the resulting packages copied to some location, can be dist directory or /tmp/output.  I have run into issues with current OnDemand deb building where if I forget to do `rm -rf build/ubuntu-20.04-1`, subsequent builds will fail.  I think intermediate files and build artifacts other than resulting package should not be output to the source tree for interactive builds.  For CI/CD builds it's fine since the source tree is cleaned up after the build.

_Originally posted by @treydock in https://github.com/OSC/ondemand-packaging/issues/112#issuecomment-951312957_

**Comment by treydock** [comment]
Closing in favor of #121 which is same.
