### ISSUE TITLE
cli functionality

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand-packaging#123]
The ability to run CLI command to do builds (can reference Ruby Rake code if we go that direction). This ensures that non-Ruby apps don't need a Rakefile and Gems as we do build many non-Ruby things.  The CLI command should take arguments that can have a help output printed, ie not using environment variables unless the help output prints possible environment variables.  It would be good to not have to read code to remember what flags / env vars are needed.

**Comment by treydock** [comment]
Closing via #159
