### ISSUE TITLE
gpg keys configurable location

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand-packaging#132]
I think long term we should remove the ondemand-packaging clone from Gitlab CI/CD and instead bootstrap GPG keys to different location and use appropriate flags to tell build scripts where to find the new GPG keys.  I can make that change now or defer, either way works. Mostly just wanted to get nightlies fixed so could apply Puppet on dev nodes.

_Originally posted by @treydock in https://github.com/OSC/ondemand/issues/1533#issuecomment-953843445_

**Comment by treydock** [comment]
Closing via #159
