### ISSUE TITLE
Naming ood vs ondemand

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand-packaging#14]
@nickjer @ericfranz 

Some packages are prefixed with `ondemand` and others are `ood`.  The repos path is also `ood`.  Ideally we'd stick to only one naming convention.  Thoughts?

**Comment by treydock** [comment]
I vote for changing all references of `ood` to `ondemand`.  Thoughts?

**Comment by treydock** [comment]
Talked with Jeremy and I'm going to do the rename to `ondemand`, repo prefix included.

**Comment by nickjer** [comment]
I am fine with `ondemand` as this is the product that the Open OnDemand organization is packaging.
