### ISSUE TITLE
Bump OnDemand to v1.3.0 tag

### ISSUE THREAD

**Issue by nickjer** [OSC/ondemand-packaging#16]
Could you bump the OnDemand version to tag `v1.3.0`?

**Comment by treydock** [comment]
FYI - RPMs built and uploaded earlier:

https://yum.osc.edu/ondemand/latest/web/el7/x86_64/ondemand-1.3.0-1.el7.x86_64.rpm
https://yum.osc.edu/ondemand/latest/web/el6/x86_64/ondemand-1.3.0-1.el6.x86_64.rpm

**Comment by nickjer** [comment]
Would it be possible to install all of these RPMs on a test server such as webdev07?

**Comment by treydock** [comment]
Can try install steps manually if you want.  I can perform them too if you'd like.

```
yum install https://yum.osc.edu/ondemand/latest/ondemand-release-web-1.3-1.el7.noarch.rpm
yum install ondemand
```
