### ISSUE TITLE
update passenger to 6.0.14

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand-packaging#196]
These messages are available in our PUN logs.

A security update is available for your version (6.0.7) of Phusion Passenger. We strongly recommend upgrading to version 6.0.14

**Comment by treydock** [comment]
Looks like the 2.1 version was bumped to 6.0.14, I'll go ahead and bump it up to 6.0.14

**Comment by treydock** [comment]
Yep, I can bump to 6.0.14 for 2.0 branch too.

**Comment by treydock** [comment]
That is really weird because the dependency has exact version number so should ignore the newer vesrion.

**Comment by treydock** [comment]
I just confirmed the Package file in build/2.1 repo for Ubuntu 20.04 still has both versions so not like only 6.0.14 exists in repos. I'll look into this more.
