### ISSUE TITLE
update websockify 

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand-packaging#212]
We release `0.8.0` of websockify with python2. Apparently RHEL 9 doesn't have python2 at all, so users would like to get rid of this dependency no their compute nodes.

Looks like there's `0.10.0` out also.  Seems like at least we should respond to/require the system python (whatever that is).

https://discourse.openondemand.org/t/websockify-from-ondemand-rpms/2112

**Comment by treydock** [comment]
Also OnDemand 2.1 requires python 3.x so this is good candidate for 2.1 but might be able to make work with 2.0 repos.  Just no real good way to test on my end.
