### ISSUE TITLE
Run systemctl daemon-reload during install and upgrade

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand-packaging#22]
The spec file for ondemand should run `systemctl daemon-reload` during install and upgrade.

**Comment by treydock** [comment]
@nickjer Because we drop in a file in `/etc/systemd/system/httpd24-httpd.service.d` we need to consider always doing `try-restart` for the `httpd24-httpd` service for systemd systems.

**Comment by nickjer** [comment]
> The spec file for ondemand should run `systemctl daemon-reload` during install and upgrade.

I stole most of my Apache related stuff from:

https://git.centos.org/blob/rpms!httpd24-httpd/f5da3f64730f0abb0da4b77f17777ed5ab2138b1/SPECS!httpd.spec

and so I didn't include that command. What does that command do? I can throw it in if necessary and it doesn't start `systemctl` if it isn't already started by the admin.

> Because we drop in a file in `/etc/systemd/system/httpd24-httpd.service.d` we need to consider always doing `try-restart` for the `httpd24-httpd` service for systemd systems.

I currently run it during an uninstallation here:

https://github.com/OSC/ondemand-packaging/blob/master/web/ondemand/ondemand.spec#L160

and during an installation/upgrade here (unless it fails to generate an OnDemand Apache config):

https://github.com/OSC/ondemand-packaging/blob/master/web/ondemand/ondemand.spec#L172

**Comment by treydock** [comment]
The daemon-reload is needed to pick up changes to unit files.  I don't think it's needed when you add a unit file but when you modify one, like what `ood.conf` does.
