### ISSUE TITLE
issues trying to build rpm locally

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand-packaging#232]
I'm trying to test the e2e tests for centos7 and am failing to build the RPM.  Not sure how why works in the CI (I'm using the same environment variables).

I can see in `docker.io/ohiosupercomputer/ood-buildbox-el7:0.5.0` `~/.rpmmacros` exists, but `~/.gnupg` does not.

```
== Bootstrap RPM ==
        Bootstrap /root
cp: cannot stat ‘/home/ood/.gnupg’: No such file or directory
rake aborted!
Command failed with status (1): [cp -r /home/ood/.rpmmacros /home/ood/.gnup...]
/ondemand-packaging/gems/gems/ood_packaging-0.5.0/lib/ood_packaging/build.rb:169:in `bootstrap_rpm!'
/ondemand-packaging/gems/gems/ood_packaging-0.5.0/lib/ood_packaging/build.rb:143:in `run!'
/ondemand-packaging/gems/gems/ood_packaging-0.5.0/lib/ood_packaging/tasks.rb:47:in `block (3 levels) in <top (required)>'
/ondemand-packaging/gems/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/ondemand-packaging/rake:23:in `load'
/ondemand-packaging/rake:23:in `<main>'
Tasks: TOP => ood_packaging:package:build
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203286793149843) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1202821104799596/1203286793149843

**Comment by treydock** [comment]
CI uses Docker.  I do all my work on OS X and Podman on OS X is useless and nothing like Linux as it has to run in some kind of Linux VM so accessing things is entirely different.  The `/home/ood/.gnupg` is supposed to be part of the container but only for DNF OSes:

https://github.com/OSC/ondemand-packaging/blob/ca1580d9a1c81ab20a8512e25cf873958d28df5d/lib/ood_packaging/build_box/docker-image/install.sh.erb#L73-L76

So looks like this is an issue where a directory in container is only created for EL8+ but the runtime logic expects it there no matter what.  See if #234 fixes your issue.
