### ISSUE TITLE
package for amazon linux 2023

### ISSUE THREAD

**Issue by mrgum** [OSC/ondemand-packaging#242]
Hello

I'd like to run open ondemand on amazon linux 2023.  it has httpd 2.4.56 but lacks epel or scl out of the box

I'm willing to do the work but I'm a bit stuck on how to build from source as ondemand seems to depend on things like ondemand-build that I don;t know where to get.

rpmbuild -ba ondemand.spec --define "package_version 3.0"
setting SOURCE_DATE_EPOCH=1549584000
error: Failed build dependencies:
	ondemand-build = 3.0.0-1.amzn2023 is needed by ondemand-3.0-1.amzn2023.x86_64
	ondemand-nodejs = 3.0.0-1.amzn2023 is needed by ondemand-3.0-1.amzn2023.x86_64
	ondemand-ruby = 3.0.0-1.amzn2023 is needed by ondemand-3.0-1.amzn2023.x86_64
	ondemand-runtime = 3.0.0-1.amzn2023 is needed by ondemand-3.0-1.amzn2023.x86_64
	ondemand-scldevel = 3.0.0-1.amzn2023 is needed by ondemand-3.0-1.amzn2023.x86_64

Thanks,

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1204443296098176) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
@johrstrom Just FYI, Amazon Linux 2023 only has Ruby 3.2 and NodeJS 18, so we'd need to validate OnDemand against Ruby 3.2 and NodeJS 18.

**Comment by treydock** [comment]
Also EPEL isn't possible with Amazon Linux 2023: https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html#epel.  So we are entirely dependent on what is in the OS repos.

**Comment by treydock** [comment]
Ah, Amazon Linux 2023 doesn't ship SCL utils.  That's going to really complicate things.

**Comment by johrstrom** [comment]
> @johrstrom Just FYI, Amazon Linux 2023 only has Ruby 3.2 and NodeJS 18, so we'd need to validate OnDemand against Ruby 3.2 and NodeJS 18.

That should be fine.

**Comment by treydock** [comment]
@mrgum Amazon Linux 2023 will be supported once OnDemand 3.1 is released.

**Comment by mrgum** [comment]
Excellent, Thank you
