### ISSUE TITLE
App specs need to define NGINX app configs

### ISSUE THREAD

**Issue by nickjer** [OSC/ondemand-packaging#25]
The app specs currently do not define an NGINX app config, so after a fresh installation of the RPM the first user of the app will experience this:

![image](https://user-images.githubusercontent.com/4260509/36903078-8b5990d8-1dfa-11e8-8c74-e25dc531db61.png)

This can be alleviated by something along the lines of:

```rpm-spec
...

%install
...
touch %{buildroot}%{_sharedstatedir}/nginx/config/apps/sys/MY_APP.conf
...

%post
...
# Generate NGINX app config during installation/upgrade
/opt/ood/nginx_stage/sbin/update_nginx_stage &>/dev/null || :

# Do not forget to restart app if it is a Passenger app
touch %{_localstatedir}/www/ood/apps/sys/MY_APP/tmp/restart.txt
...

%postun
...
if [[ $1 -eq 0 ]]; then
  # Clean up NGINX app config after uninstallation
  /opt/ood/nginx_stage/sbin/update_nginx_stage &>/dev/null || :
fi
...

%files
...
%ghost %{_sharedstatedir}/nginx/config/apps/sys/MY_APP.conf
...
```

**Comment by treydock** [comment]
@nickjer I updated the app spec template.  Any other places this change would be needed besides future passenger apps and the actual ondemand package?
