### ISSUE TITLE
Debian 12 support

### ISSUE THREAD

**Issue by severgun** [OSC/ondemand-packaging#251]
After all that drama around RHEL rising paywall for CentOS sources future of Rocky/Alma/Oracle not clear. Maybe it's time to consider to add Debian Stable support on par with Ubuntu LTS?

Debian 12 currently have.
Apache 2.4.57
Ruby - 3.1
bundler - 2.3.15
nodejs - 18.13

Seems like only ruby version blocking from installing jammy debs in Debian 12.

Also if you use Docker to build project. Why not to provide docker official images like gitlab as an example? What is the stopping factor? That will make it distro agnostic.

**Comment by johrstrom** [comment]
> Debian 12 currently have.
> Apache 2.4.57
> Ruby - 3.1
> bundler - 2.3.15
> nodejs - 18.13

I think with these versions we could easily support Debian 12 - we can use this ticket to do so.

> Also if you use Docker to build project. Why not to provide docker official images like gitlab as an example? What is the stopping factor? That will make it distro agnostic.

I feel like running production OOD in a container is a bit odd. the per user nginx (PUN) architecture allows us to sort of isolate different users.  Plus all the forking it would require. It'd require the container to run as root and then would require the container to be allowed to fork into _all_ users.  

It just seems too insecure & prone to issues  - at least to me. I know of at least one site that does this, but I hesitate to recommend it for the reasons given. Maybe @treydock has more to say about it.
