### ISSUE TITLE
debian nodejs apt source change

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand-packaging#261]
This sources.list file doesn't work anymore apparently. Our CI started failing this morning unable to find nodejs 18.

https://github.com/OSC/ondemand-packaging/blob/43b39cf6b663599756cc13960b64950c2ecf36d3/packages/ondemand-release/deb/debian/rules#L29

Apparently `CODENAME` is unused and should be hard coded to `nodistro`. 

See this issue for more information:
https://github.com/nodesource/distributions/issues/1706

**Comment by treydock** [comment]
@johrstrom Is this affecting OnDemand 3.0 or just 3.1?

**Comment by johrstrom** [comment]
It's likely affecting both.  I mean this line in a source file will return 404 since today (I'm guessing today just because it's the first of the month and yesterday the CI was working fine)

```
deb https://deb.nodesource.com/18.x jammy main
```

https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository
