### ISSUE TITLE
update turbovnc and python-websockify

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand-packaging#268]
update turbovnc and python-websockify to the current applicable versions for the 3.1 release.

**Comment by CSC-swesters** [comment]
I see that this was committed just an hour ago, so sorry for being late once again!
Isn't `3.1.1` the latest TurboVNC release currently? Based on their Github releases: https://github.com/TurboVNC/turbovnc/releases

**Comment by CSC-swesters** [comment]
Big thanks! I checked that https://www.turbovnc.org/ has a link to their Github releases with the text "Official Binaries and Source Tarballs", so I would assume that it's a safe source to pull from.
