### ISSUE TITLE
"v" for version appended to git annex command.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ondemand-packaging#27]
The `git annex` command at https://github.com/OSC/ondemand-packaging/blob/master/mk_app_spec.sh#L29 appends a `v` to the version. This is causes the error like this:

```
± |systemstatus ✓| → ./mk_app_spec.sh osc-systemstatus systemstatus v1.4.0
Getting https://github.com/OSC/osc-systemstatus/archive/vv1.4.0.tar.gz to ./vv1.4.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
git-annex: vv1.4.0.tar.gz not found
```

Adding a "v" to the beginning of the github version tag I think is just an internal convention, and it's possible that some repos may not be tagged this way. (i.e. `1.4.0` instead of `v1.4.0`) So it may not be safe to make this assumption.

**Comment by brianmcmichael** [comment]
Hmm, there's also the assumption that the repo is in the `github.com/OSC` organization. System Status currently resides in the `github.com/AweSim-OSC` organization, so I'm still getting errors.

**Comment by treydock** [comment]
README updated to help with version issue to show the version expected is `1.4.0` and the assumption is the tag starts with `v`.  The fact the repo is different is somewhat unavoided, the template generates something that has to be modified based on the app being created.
