### ISSUE TITLE
Get individual app specs

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand-packaging#3]
@nickjer @ericfranz 

List of apps that we need to build RPMs for that are not part of ondemand RPM:

- [x] https://github.com/AweSim-OSC/osc-systemstatus 1.4.0
- [x] https://github.com/OSC/bc_osc_abaqus/tree/v0.2.0
- [x] https://github.com/OSC/bc_osc_ansys_workbench/tree/v0.2.0
- [x] https://github.com/OSC/bc_osc_comsol/tree/v0.2.0
- [x] https://github.com/OSC/bc_osc_jupyter/tree/v0.3.0
- [x] https://github.com/OSC/bc_osc_jupyter_spark/tree/v0.0.3
- [x] https://github.com/OSC/bc_osc_matlab/tree/v0.1.0
- [x] https://github.com/OSC/bc_osc_paraview/tree/v0.2.0
- [x] https://github.com/OSC/bc_osc_rstudio_server/tree/v0.3.0
- [x] https://github.com/OSC/pseudofun/tree/v0.1.0
- [x] https://github.com/OSC/bc_osc_ansys_workbench/releases/tag/v0.2.0-PMIU0149

Non Apps
- [x] https://github.com/OSC/ood_auth_discovery/tree/v0.2.0
- [x] https://github.com/OSC/ood_auth_registration/tree/v0.2.0

**Comment by treydock** [comment]
What about bc_osc_ansys_workbench_PMIU0149?

**Comment by nickjer** [comment]
I think that should also be ported to an RPM. Although that is a branch.

**Comment by treydock** [comment]
For bc_osc_ansys_workbench_PMIU0149, would be possible to get a tag associated with that branch?  Maybe PMIU0149-<ver> or something?

**Comment by treydock** [comment]
Looking at web05 / ood.osc.edu, I see apps not yet accounted for.  Do we need to package these?

* bc_example_jupyter
* osc_bc_abaqus_simple

**Comment by nickjer** [comment]
I do not believe so. Those are mostly used as tutorials for other centers to start with when building the corresponding app.
