### ISSUE TITLE
Update app template for GitLab (various owners) and other GitHub Organizations

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand-packaging#30]
So far, https://github.com/OSC/ondemand-packaging/blob/master/app.spec assumes these two things:

```
URL:      https://github.com/OSC/%{repo_name}
Source0:  https://github.com/OSC/%{repo_name}/archive/v%{version}.tar.gz
```

Two problems exist when using a GitLab repo.

1. Manually replace https://github.com/OSC with https://code.osu.edu/wiag
2. Modify suffix URL to match GitLab's
2. Append URL fragment to trick spectool to rename GitLab's archive.tar.gz to version file

Perhaps we do this:

```diff
# Disable debuginfo as it causes issues with bundled gems that build libraries
 %global debug_package %{nil}
 %global repo_name REPO_NAME
+%global repo_owner REPO_OWNER
+%global gitlab 0
 %global app_name APP_NAME
 %global with_passenger 1
```

And

```diff
 Group:    System Environment/Daemons
 License:  MIT
-URL:      https://github.com/OSC/%{repo_name}
+URL:      %{repo_owner}/%{repo_name}
-Source0:  https://github.com/OSC/%{repo_name}/archive/v%{version}.tar.gz
+%if 0%{?gitlab}
+Source0:  %{repo_owner}/%{repo_name}/repository/v%{version}/archive.tar.gz#/v%{version}.tar.gz
+%else
+Source0:  %{repo_owner}/%{repo_name}/archive/v%{version}.tar.gz
+%endif
```

**Comment by treydock** [comment]
The template is not intended to work out of the box for any app because it has place holders for things like description and summary so some amount of manual edits are always going to be necessary.  The template was intended to require fewest changes for the majority of apps which are the interactive apps.

**Comment by treydock** [comment]
Maybe update template generation script if want to handle those conditions instead of adding more edge cases to spec file. If majority of apps will come from github then seems okay to leave as-is but feel free to make changes if would help yall.
