### ISSUE TITLE
rpms contain production.log files that are produced when running rake tasks

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand-packaging#31]
```
efranz@webtest02:~$ rpm -ql ondemand-1.3.7-1.el6.x86_64 | egrep production.log$
/var/www/ood/apps/sys/activejobs/log/production.log
/var/www/ood/apps/sys/dashboard/log/production.log
/var/www/ood/apps/sys/file-editor/log/production.log
/var/www/ood/apps/sys/myjobs/log/production.log
efranz@webtest02:~$ rpm -ql ondemand-pseudofun-0.2.0-1.el6.x86_64 | egrep production.log$
/var/www/ood/apps/sys/pseudofun/log/production.log
```

Any production.log files produced should be removed, or when running rake tasks we should determine how to avoid producing these in the first place. In OnDemand apps log to STDOUT which is then gathered by NGINX.

When these files exist, the Rails app logs are polluted with these warning messages:

>App 25936 stderr: Rails Error: Unable to access log file. Please ensure that /users/PZS0645/wiag/ood_portals/ondemand_test/sys/dashboard/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /users/PZS0645/wiag/ood_portals/ondemand_test/sys/dashboard/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.

**Comment by treydock** [comment]
Resolved via https://github.com/OSC/ondemand-packaging/commit/8a810bace0e7ef3e7beae73cc44a0644e47fd764

**Comment by treydock** [comment]
I have pushed the updated packages for `ondemand`, 'ondeand-systemstatus' (https://github.com/OSC/ondemand-packaging/commit/2b26d1aab9f4fe232123f339104ffdd97f9d746a), and `ondemand-pseudofun` to test nodes.

I verified the updated packages did remove `production.log` from the previous locations.

Let me know when want these updates in production.

**Comment by treydock** [comment]
RPMs pushed to production.
