### ISSUE TITLE
Automate updating specs to new versions

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand-packaging#32]
Trey and I discussed this offline (haven't found the email exchange yet) but it would be nice to start working on some automation of updating the spec files when switching to a new version.

A Rake file in the root of the repo might be sufficient (use Rake.original_dir to see where you ran the task). Usage would be something like cd to a particular spec's directory, run `rake update v2.5.0` and it would modify the file, do the test rpm build, verify it worked, if it did either ask you to run the same command again to build and release the rpm, making the appropriate commits etc.

**Comment by ericfranz** [comment]
But this should wait till we move OnDemand to a single 1 repo, because then that spec can become much simpler

**Comment by treydock** [comment]
This was solved by removing version from spec and having it passed in at build time.
