### ISSUE TITLE
Revert back to mirror.centos.org for SCLo repos on EL6 after upgrading SCLo packages

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand-packaging#33]
See ea400344eaa5c6e0f3cbd380eafc8a22b5aa2a18

We should upgrade to later supported SCL packages prior to releasing a stable version of OnDemand 1.4

**Comment by treydock** [comment]
This was fixed in revert d265115d6cbca8f31da584d58c61da90d42c4e0d
