### ISSUE TITLE
Upgrade Ruby, Node, and Git SCL packages

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand-packaging#34]
See https://www.softwarecollections.org/en/scls/rhscl/rh-ror50/ 

> This Software Collection is supported together with the rh-ruby24 and rh-nodejs6 Collections.

So the suggestion is to update depenencies to rh-ruby24, rh-nodejs6, and rh-git29 which are available for both EL6 & EL7. While there exist rh-nodejs8 and rh-ruby25 these are only for EL7.

https://access.redhat.com/support/policy/updates/rhscl

**Note: rh-git29 end of life is Nov 2018 which is in a month.**

Also other repos will need changes to support this:

**The Fixnum and Bignum classes integrated into the Integer class** 

The best thing to do is install the packages on webdev02 and then update the components & apps and test. Then create new release versions of the components & apps and then create the new rpms.

Example of places to change (not including readmes and other documentation):

1. rh-ruby22 - https://github.com/search?q=org%3AOSC+rh-ruby22+-extension%3Amd+-extension%3Arst&type=Code
2. git19 - https://github.com/search?q=org%3AOSC+git19+-extension%3Amd+-extension%3Arst&type=Code
3. nodejs010 - https://github.com/search?q=org%3AOSC+nodejs010+-extension%3Amd+-extension%3Arst&type=Code

and not including the spec files:

1. rh-ruby22 - https://github.com/search?q=org%3AOSC+rh-ruby22+-extension%3Amd+-extension%3Arst+-extension%3Aspec&type=Code
2. git19 - https://github.com/search?q=org%3AOSC+git19+-extension%3Amd+-extension%3Arst+-extension%3Aspec&type=Code
3. nodejs010 - https://github.com/search?q=org%3AOSC+nodejs010+-extension%3Amd+-extension%3Arst+-extension%3Aspec&type=Code

which looks a lot less dangerous.

**Comment by treydock** [comment]
Are any changes still needed here?  rh-git29 being EOL is unfortunate but SCLo doesn't have expiration date: https://www.softwarecollections.org/en/scls/rhscl/rh-git29/ and https://wiki.centos.org/SpecialInterestGroup/SCLo/CollectionsList

**Comment by ericfranz** [comment]
Closing this, as we have upgraded to rh-git29, rh-ruby24, rh-nodejs6. While rh-nodejs6 is EOL April 2019 and rh-git29 is already EOL, SCLo doesn't have expiration on those and those are the latest versions that have RHEL6 support. The later ones do not have RHEL6.
