### ISSUE TITLE
Add Jupyter Pitzer rpm

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand-packaging#35]
https://github.com/OSC/bc_osc_jupyter_pitzer

**Comment by MorganRodgers** [comment]
Noted. I'll handle this after the ondemand build.

**Comment by MorganRodgers** [comment]
https://code.osu.edu/osc/osc-puppetmaster-conf/merge_requests/69

**Comment by MorganRodgers** [comment]
In prod.
