### ISSUE TITLE
Build native support for SCL Ruby 

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand-packaging#39]
The nginx logs currently get proliferated with this error:

```
App 4403 output:  [passenger_native_support.so] not found for current Ruby interpreter.
App 4403 output:      This library provides various optimized routines that make
App 4403 output:      Phusion Passenger faster. Please run 'sudo yum install passenger-devel-5.3.7'
App 4403 output:      so that Phusion Passenger can compile one on the next run.
App 4403 output:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
App 4403 output:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 4403 output:      Could not download https://github.com/phusion/passenger/releases/download/release-5.3.7/rubyext-ruby-2.4.3-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
App 4403 output:      Trying next mirror...
App 4403 output:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.3.7/rubyext-ruby-2.4.3-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
App 4403 output:      Trying next mirror...
App 4403 output:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.3.7/rubyext-ruby-2.4.3-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
App 4403 output:  [passenger_native_support.so] will not be used (can't compile or download)
App 4403 output:   --> Passenger will still operate normally.
```

We can suppress these errors with a config option, but it might be preferable to determine how to build `passenger_native_support.so` for SCL Ruby we are using.

The failed download is: https://github.com/phusion/passenger/releases/download/release-5.3.7/rubyext-ruby-2.4.3-x86_64-linux.tar.gz

This is because https://github.com/phusion/passenger/releases/tag/release-5.3.7 has rubyext-ruby-2.4.4-x86_64-linux.tar.gz not rubyext-ruby-2.4.3-x86_64-linux.tar.gz.

If the passenger_native_support.so was built for the SCL Ruby we are using for apps, presumably Ruby based Passenger apps would start up faster.

**Comment by ericfranz** [comment]
I can reproduce this via command line on the Vagrant image:

```
[vagrant@localhost ~]$ sudo scl enable rh-ruby24 -- passenger-config build-native-support
 [passenger_native_support.so] not found for current Ruby interpreter.
     This library provides various optimized routines that make
     Phusion Passenger faster. Please run 'sudo yum install passenger-devel-5.3.7'
     so that Phusion Passenger can compile one on the next run.
 [passenger_native_support.so] finding downloads for the current Ruby interpreter...
     (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
     Could not download https://github.com/phusion/passenger/releases/download/release-5.3.7/rubyext-ruby-2.4.3-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
     Trying next mirror...
     Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.3.7/rubyext-ruby-2.4.3-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
     Trying next mirror...
     Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.3.7/rubyext-ruby-2.4.3-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
 [passenger_native_support.so] will not be used (can't compile or download)
  --> Passenger will still operate normally.
```

Not sure how to tell Passenger which mirrors to use...

**Comment by ericfranz** [comment]
Ah it requires this file: https://github.com/phusion/passenger/blob/b30bdbe66b3f41d108f160e22778549ef82184d3/src/ruby_supportlib/phusion_passenger/native_support.rb

**Comment by treydock** [comment]
@ericfranz That file exists but is not in Ruby's path most likely for SCL as it's at `/usr/share/ruby/vendor_ruby/phusion_passenger/native_support.rb`.

**Comment by treydock** [comment]
If we build the native support for SCL ruby it should probably be done in the ondemand spec to avoid having to modify the passenger RPM spec since we pull that from passenger.

**Comment by ericfranz** [comment]
This looks interesting:

https://github.com/phusion/passenger/blob/b30bdbe66b3f41d108f160e22778549ef82184d3/src/ruby_supportlib/phusion_passenger/native_support.rb#L85-L98

in particular: PASSENGER_NATIVE_SUPPORT_OUTPUT_DIR

**Comment by ericfranz** [comment]
>That file exists but is not in Ruby's path most likely for SCL as it's at /usr/share/ruby/vendor_ruby/phusion_passenger/native_support.rb

I thought it had to be built separately for each Ruby version. I could be wrong though.

**Comment by ericfranz** [comment]
https://github.com/phusion/passenger/blob/b30bdbe66b3f41d108f160e22778549ef82184d3/src/ruby_supportlib/phusion_passenger/native_support.rb#L255-L271 is where it looks for the mirrors to download

**Comment by ericfranz** [comment]
Yeah. It does look like we can define a custom `PASSENGER_NATIVE_SUPPORT_OUTPUT_DIR` env var to point to wherever we want for the custom built rh-ruby24 extension.

Ah, so if we need to have rh-ror50 to build it then would that make rh-ror50 a dependency of OnDemand? If so, it was something we were wanting to do - explore switching to using system gems instead of vendor-izing the gems for each of our apps. Though as you say rh-ror50 gems are not updated that often.

So maybe this is something we should explore after the 1.5 release at the end of January and for now just suppress the warnings...

I think it would help some with performance but I do not know how much or where unfortunately. I was hoping it might impact startup time for some Passenger apps.

**Comment by treydock** [comment]
I don't see how `PASSENGER_NATIVE_SUPPORT_OUTPUT_DIR` would help since we need to build native support specific to `rh-ruby24` and when building packages against SCL is typically good to use SCL-like paths.

```
$ rpm -qpl /tmp/output/el7/passenger-passenger-5.3.7-1.el7.x86_64.rpm  | grep native
/opt/rh/passenger/root/usr/lib64/ruby/vendor_ruby/passenger_native_support.so
/opt/rh/passenger/root/usr/share/ruby/vendor_ruby/phusion_passenger/config/build_native_support_command.rb
/opt/rh/passenger/root/usr/share/ruby/vendor_ruby/phusion_passenger/native_support.rb
/opt/rh/passenger/root/usr/share/ruby/vendor_ruby/phusion_passenger/utils/native_support_utils.rb
```

**Comment by treydock** [comment]
My experiment is not working, for some reason I can't figure out the RPM generated requires `/opt/rh/passenger/root/usr/bin/ruby` which doesn't exist.  I am guessing somewhere in install process a header gets something like `#!/opt/rh/passenger/root/usr/bin/ruby` added because prefix is changed from `/` to `/opt/rh/passenger/root`.  Might be easier to come up with our own spec rather than trying to get standard spec to use SCL.

**Comment by treydock** [comment]
I experimented with not putting passenger at /opt/rh/passenger but installing the Ruby code to rh-ruby24 paths and this works but the RPM ends up depending on `/usr/bin/ruby` likely because RPM builds will scan executables and depend on paths found in `#!` at the top of executables.  If we modify the passenger RPM I'd recommend we make it an SCL package and add some hacks that replace `#!/usr/bin/ruby` with `#!/usr/bin/env ruby` to fix auto-requires of RPM.
