### ISSUE TITLE
When rpm installation occurs, old sprockets manifests should be deleted

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand-packaging#42]
On webtest04 the rpm that is currently installed provides only one sprockets manifest file:

```
efranz@webtest04:/var/www/ood/apps/sys/activejobs$ rpm -q -l ondemand | grep sprockets | grep activejobs | grep -v vendor
/var/www/ood/apps/sys/activejobs/public/assets/.sprockets-manifest-6237307bdf0f956506c63847c6926e6d.json
```

However, during deployment, the previously existing sprockets manifest file is still there:

```
efranz@webtest04:/var/www/ood/apps/sys/activejobs$ ls -l public/assets/ | grep sprockets
-rw-r--r-- 1 root root  24889 Feb  5 17:10 .sprockets-manifest-6237307bdf0f956506c63847c6926e6d.json
-rw-r--r-- 1 root root  24889 Dec 19 16:12 .sprockets-manifest-9db4bf66d19a4891fb41f40beef983d5.json
```

The result is that Rails is loading the older manifest. The code used to load that is here:

```
irb(main):005:0* Sprockets::ManifestUtils.find_directory_manifest "public/assets"
=> "public/assets/.sprockets-manifest-9db4bf66d19a4891fb41f40beef983d5.json"
```

The result of picking the wrong manifest is that the HTML includes the wrong path to the recently updated asset i.e. `js`:

```html
<script src="/pun/sys/activejobs/assets/application-4cba4d08a3459569e5efd569cccf006dc773fc4cd619be48537b47fbf0184146.js"></script>
```

This is produced by Rails looking at the older `.sprockets-manifest-9db4bf66d19a4891fb41f40beef983d5.json` and not the newer `.sprockets-manifest-6237307bdf0f956506c63847c6926e6d.json` for the url to application.js so then a 404 response is returned for the JS and the app fails to work.

```

**Comment by treydock** [comment]
`.sprockets-manifest-9db4bf66d19a4891fb41f40beef983d5.json` Only existed on 2 of the OSC test nodes and nothing else.  I checked all other OnDemand nodes and they all have sprocket files owned by the ondemand package.  I think this may be something that got left behind during bad packages that we tested at some point.  I have removed the roque sprockets file and verified the one on production is owned by ondemand package so it would get removed during upgrade.

**Comment by treydock** [comment]
Also because this file is owned by a package it's not safe or advised to do any kind of %post removal.  If the file got left behind then something was broken with package that got deployed on Dec 19th (date of rogue file).

**Comment by ericfranz** [comment]
This was reproduced at TAMU

**Comment by treydock** [comment]
@ericfranz Per my email comments, there's not much we can do if sprockets are getting created that are not part of previous RPMs.  The files that existed both at OSC and TAMU are not a part of any RPM we've ever built so they have to have been generated outside packaging which means there's not much to do for packages.

If we wanted to come up with a way to clean old sprockets, we'd run the risk of deleting files that do belong to RPMs which will generate errors during RPM updates.  The names aren't static in the two cases so if we just did "rm /path/to/.sprockets-manifest*" we'd run the risk of deleting packaged files and thus generating RPM validation errors.

**Comment by novosirj** [comment]
Rutgers ran into the same issue, upgrading from 1.3 to 1.6. We had multiple .sprockets-manifest files for the dashboard, the active jobs listing, and maybe one or two others. I'm not sure if we at some point installed independent of the RPMs or whether there was a packaging bug in the past that caused this.

**Comment by treydock** [comment]
The only way I was able to reproduce this was building assets on a system where assets had been installed via the RPM. The files that get installed by the RPM are removed upon upgrade as part of standard behavior of RPM packaging.
