### ISSUE TITLE
Update the nginx_clean cron job to pipe stderr and stdout to syslog

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand-packaging#50]
See https://github.com/OSC/ondemand/pull/36#issuecomment-488109713

**Comment by treydock** [comment]
Looks like OSC's cron job differs from the one in RPM. I don't think we should be using `update_nginx_stage` via cron should we?  That does `app_clean`, `app_reset --sub-uri=/pun` and `nginx_clean`.  If we use `update_nginx_stage` for cron then the script needs some updates.

OSC:

```
/opt/ood/nginx_stage/sbin/nginx_stage nginx_clean 1>/dev/null
```

RPM:

```
/opt/ood/nginx_stage/sbin/update_nginx_stage --quiet
```

**Comment by treydock** [comment]
If we really need all 3 of those subcommands via cron then I'd suggest a new wrapper script.

**Comment by treydock** [comment]
@ericfranz @MorganRodgers Thoughts on what the cron job should look like?  If all we need is `nginx_clean` then that would be simpler. If we really need all the subcommands used by `update_nginx_stage` then I would opt for a new wrapper just for cron.

**Comment by ericfranz** [comment]
FYI "--quiet" only affects this:

https://github.com/OSC/ondemand/blob/01731b790eaf4ee69f343899efd4fa5f73e36003/nginx_stage/sbin/update_nginx_stage#L27-L29

**Comment by ericfranz** [comment]
Looks like this is run during an upgrade https://github.com/OSC/ondemand-packaging/blob/6cf47b0cc31214b4e8d05780cbe2dc6c59493f0f/web/ondemand/ondemand.spec#L230

So unless you are doing heavy app development or actively modifying the pun configs, I don't see a reason to execute app_clean and app_reset in the cron. So I'm okay if the cron in the rpm would change to be just nginx_clean.

If there is no problem with this change being applied when OnDemand is being updated (changing from update_nginx_stage to nginx_clean) then I'm okay with it for the cron. I assume we would just be changing https://github.com/OSC/ondemand-packaging/blob/6cf47b0cc31214b4e8d05780cbe2dc6c59493f0f/web/ondemand/ondemand.spec#L123-L127

**Comment by ericfranz** [comment]
FWIW I would like to fix the proxy in the next 6 months so that app configs are auto-generated based on a scan of the apps a user has access to when generating the PUN config at startup, eliminating the need for this `app_clean` command

**Comment by treydock** [comment]
That spec is where it would change, and for OSC also in Puppet to make the changes match.  The spec defines that cron file as a config file so it will only be modified if a site has not made changes to the file.  We will have to document in release notes the change so people who have modified the cron job are aware they need to possibly make changes.

**Comment by treydock** [comment]
Closing via #51
