### ISSUE TITLE
Build Failure: UID already exists in container

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand-packaging#56]
After pulling master I am no longer able to build RPMs. I get the error:

    ERROR: you can only run this script with a user whose UID does not already exist in the Docker container. Current UID: 972441478

Logs attached: [el6.zip](https://github.com/OSC/ondemand-packaging/files/3339647/el6.zip)

**Comment by treydock** [comment]
Pull master again. I just removed that sanity check because it was breaking automated builds with Gitlab.

**Comment by MorganRodgers** [comment]
Confirmed working now. Thanks.
