### ISSUE TITLE
Docker build issues on MacOS

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand-packaging#60]
@johrstrom @ericfranz @MorganRodgers 

Just a warning, I upgraded to Docker Desktop 2.1.0.0 on MacOS and now I can't build using this repo. The issue is the root cache I added is getting extracted using `gtar` and seems to generate this error: `Directory renamed before its status could be extracted`. This I think has something to do with the underlying filesystem used for the running container.

I am experimenting with changing how the cache is stored in the `ondemand_buildbox` image to maybe avoid the tar extraction part.

**Comment by johrstrom** [comment]
Yea I get this error with rootless podman on Linux, which could be similar? I ended up having to run as root. I tried all sorts of hacks to get tar to use `--no-same-owner`, but it didn't work.  Probably not the exact same issue given they're different platforms, but I thought I'd at least document this somewhere.

`gtar: ./usr/sbin/arping: Cannot change ownership to uid 0, gid 0: Operation not permitted`.

**Comment by johrstrom** [comment]
If I were asked, I'd suggest we move to 2 smaller images (for 6 and 7) that just run `rpmbuild` and `gpg sign` and so on.  I think running `run` is a lot simpler of a model than managing the lifecycle with run/exec/kill.  

Fix the cache issue by getting rid of it. Just my two cents.

**Comment by treydock** [comment]
Problem with that is using mock has a lot of advantages like dependency resolution for builds. If we removed mock the only way to keep fast builds would be to install all possible dependencies into the main docker build image and that's poor practice for reproducible builds.  The mock cache is a starting point and it handles updating the build environment to meet needs of a particular RPM spec. We might be able to mimic that behavior in the build scripts but it'd be challenging.

**Comment by treydock** [comment]
The bigger issue is interoperability of Docker on Mac OS vs Linux.  The CI/CD pipeline uses Docker in Linux but several of us like to build in MacOS and Docker behaves very differently there.

**Comment by treydock** [comment]
I've fixed the issue here: https://github.com/OSC/ondemand-packaging/commit/86c692ac75a8a699d18d4b50a578770ce0874c61

If we keep having issues with mock I might be able to remove it and just rely on build environment being the docker container.

**Comment by treydock** [comment]
Removing mock isn't an option unless we use a docker container per OS we support. We can even build OpenSUSE RPMs using mock from a CentOS 7 container. I'm going to close this.
