### ISSUE TITLE
Consider Updating TurboVNC

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand-packaging#71]
A site has reported issues where OSC's hosted version of TurboVNC will not start (https://discourse.osc.edu/t/turbovnc-in-yum-ondemand-repo-outdated/540). This appears to be a known issue (https://github.com/TurboVNC/turbovnc/issues/136) which has been fixed in newer releases.

We should consider updating.

**Comment by treydock** [comment]
I'm fine updating but be good to update the version at OSC to match so we know what we are pushing out actually works. The version at OSC on Owens looks to be 2.1.90 which is what I've added to #69 which is work for 1.7.

Can we update to latest version at OSC too?

**Comment by treydock** [comment]
Also it would be good to know exactly how TurboVNC is built at OSC and what cmake output looks like, like if we build with openssl support and other optional features.
