### ISSUE TITLE
OOD 1.7 upgrade broke log rotation

### ISSUE THREAD

**Issue by azric** [OSC/ondemand-packaging#87]
The OnDemand 1.7 update of
`ondemand-nginx-1.17.3-3.p6.0.4.el7.x86_64`
changed /etc/logrotate.d/ondemand-nginx's create line from
`   create 0644 ondemand-nginx ondemand-nginx`
to
`   create 0644 nginx nginx`
However, there's no nginx entry in /etc/passwd on my fairly recently built dev server. 

I've changed the OnDemand-nginxcreate line back to the 1.6
`  create 0644 ondemand-nginx ondemand-nginx`
just to get things rolling again, but I'm not sure this is the correct long term solution.

**Comment by treydock** [comment]
Moved issue to repo responsible for the bug.

@azric  Thanks for catching this.  I've pushed `ondemand-nginx-1.17.3-5.p6.0.4.el7.x86_64` to `1.7` repos with the needed fix from #88 . If you update the latest RPM it will likely create a `/etc/logrotate.d/ondemand-nginx.rpmnew` file that will have to be moved to `/etc/logrotate.d/ondemand-nginx`.
